### ISSUE TITLE
Optimise out "equivalent" connections from Ensembles

### ISSUE THREAD

**Issue by mundya** [project-rig/nengo_spinnaker#49]
There are some cases where there are lots of "equivalent" connections coming from Ensembles, e.g.:

``` python
nengo.Connection(a, b)
nengo.Connection(a, c)
```

It might be beneficial to combine these together (on SpiNNaker) so that the same value is sent for each connection, i.e, they will share a decoder matrix.  As this is equivalent to using cached decoders I'm guessing there is no reason that this can't be done?

@tcstewar do you have any thoughts/concerns regarding this?

**Comment by neworderofjamie** [comment]
I'm sure you've thought of this, but make sure they don't have PES!

**Comment by tcstewar** [comment]
> It might be beneficial to combine these together (on SpiNNaker) so that the same value is sent for each connection, i.e, they will share a decoder matrix. As this is equivalent to using cached decoders I'm guessing there is no reason that this can't be done?

Ah, I Actually didn't know that wasn't done already.  Yup, we should only compute one decoder there and we should only store it once.

I actually have some code I've been working on to collapse together all the Connections coming out of an Ensemble into one big decoder (inspecting the Connection slices and function and solver to make sure it's allowed).  However, it's all happening at the nengo level (as it it creates a passthrough node and sets it up so that the Ensemble only has one output Connection, and that one Connection goes to the new passthrough Node), so it might not be useful here.

**Comment by mundya** [comment]
This was managed in #66.
